---
# tasks file for docker

- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  loop: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']

- name: add docker official gpg key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: check fingerprint
  command: apt-key fingerprint 0EBFCD88
  register: fingerprint_result
  
- name: print stdout for fingerprint
  debug:
    msg: "{{fingerprint_result}}"
      
- name: add docker apt repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
    state: present

- name: install docker
  package: 
    name: docker-ce
    state: present
  register: result
    
- name: restart docker if changes were made
  service:
    name: docker
    state: started
  become: true
  when: result.changed

- name: Adding ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
  
- name: stop old docker container
  shell: docker stop $(docker ps -aq)

- name: adding required shell command to install nginx
  shell:
    cmd: docker run -d -p 8080:80 nginx
